global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/prometheus-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'mailpit'
    static_configs:
      - targets: ['mailpit:8025']
      
  - job_name: 'zot'
    metrics_path: /metrics
    static_configs:
      - targets: ['zot:5000']

  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['keycloak:18080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'valkey'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'elasticsearch'
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: ['localhost:9200']        # requires ES Prometheus endpoint/exporter

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
