pg_replication:
  query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) as lag"
  metrics:
    - lag:
        usage: "GAUGE"
        description: "Replication lag behind master in seconds"

pg_postmaster:
  query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
  metrics:
    - start_time_seconds:
        usage: "GAUGE"
        description: "Time at which postmaster started"

pg_stat_activity:
  query: |
    SELECT
      datname,
      state,
      count(*) as count
    FROM pg_stat_activity
    GROUP BY datname, state
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - state:
        usage: "LABEL"
        description: "Connection state"
    - count:
        usage: "GAUGE"
        description: "Number of connections in this state"

pg_stat_database:
  query: |
    SELECT
      datname,
      xact_commit,
      xact_rollback,
      blks_read,
      blks_hit,
      tup_returned,
      tup_fetched,
      tup_inserted,
      tup_updated,
      tup_deleted,
      conflicts,
      temp_files,
      temp_bytes,
      deadlocks,
      blk_read_time,
      blk_write_time
    FROM pg_stat_database
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - xact_commit:
        usage: "COUNTER"
        description: "Number of transactions committed"
    - xact_rollback:
        usage: "COUNTER"
        description: "Number of transactions rolled back"
    - blks_read:
        usage: "COUNTER"
        description: "Number of disk blocks read"
    - blks_hit:
        usage: "COUNTER"
        description: "Number of buffer hits"
    - tup_returned:
        usage: "COUNTER"
        description: "Number of rows returned"
    - tup_fetched:
        usage: "COUNTER"
        description: "Number of rows fetched"
    - tup_inserted:
        usage: "COUNTER"
        description: "Number of rows inserted"
    - tup_updated:
        usage: "COUNTER"
        description: "Number of rows updated"
    - tup_deleted:
        usage: "COUNTER"
        description: "Number of rows deleted"
    - conflicts:
        usage: "COUNTER"
        description: "Number of queries canceled due to conflicts"
    - temp_files:
        usage: "COUNTER"
        description: "Number of temporary files created"
    - temp_bytes:
        usage: "COUNTER"
        description: "Amount of data written to temporary files"
    - deadlocks:
        usage: "COUNTER"
        description: "Number of deadlocks detected"
    - blk_read_time:
        usage: "COUNTER"
        description: "Time spent reading data file blocks"
    - blk_write_time:
        usage: "COUNTER"
        description: "Time spent writing data file blocks"
