filebeat.inputs:
# PostgreSQL logs
- type: log
  enabled: true
  paths:
    - /logs/postgres/*.log
  tags: ["postgres"]
  fields:
    service: postgres
  fields_under_root: true

# Valkey logs
- type: log
  enabled: true
  paths:
    - /logs/valkey/*.log
  tags: ["valkey"]
  fields:
    service: valkey
  fields_under_root: true

output.elasticsearch:
  hosts: ["https://es:9200"]
  index: "logs-%{+yyyy.MM.dd}"
  username: "elastic"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/ca.crt"]
  ssl.verification_mode: "certificate"

logging.level: debug
